In [1]:
import numpy as np

### numpy

 ### Accessing 

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a.ndim

1

In [5]:
a[4]

np.int64(5)

In [6]:
a[-3]

np.int64(3)

In [7]:
a[0:4:2]

array([1, 3])

In [8]:
a[::-1]


array([5, 4, 3, 2, 1])

In [10]:
b

array([[3, 5, 0],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)

In [11]:
b[0][1]

np.int32(5)

In [13]:
b[2,2]

np.int32(3)

In [14]:
b[-1][0]

np.int32(1)

In [15]:
b[-2][-2]

np.int32(8)

In [16]:
b[-2,-2]

np.int32(8)

In [17]:
b[-3][-3]

np.int32(3)

In [18]:
# Slicing

In [19]:
# b[row starting : row ending , no of colum ]

In [20]:
b[0:3,1]

array([5, 8, 2], dtype=int32)

In [21]:
b[0:3,:1] # since 

array([[3],
       [7],
       [1]], dtype=int32)

In [22]:
b[1]

array([7, 8, 9], dtype=int32)

In [24]:
b[:1]

array([[3, 5, 0]], dtype=int32)

In [25]:
b[:,1]

array([5, 8, 2], dtype=int32)

In [26]:
# 3D

In [27]:
c = np.random.randint(0,99, size=(3,3,3))

In [28]:
c

array([[[ 7, 79, 33],
        [56, 89, 32],
        [38, 76,  0]],

       [[58, 23, 39],
        [20, 73, 92],
        [96, 17, 33]],

       [[72, 36, 52],
        [54, 84, 56],
        [55, 64, 51]]], dtype=int32)

In [29]:
c[0,2,2]

np.int32(0)

In [30]:
c[0:3,2,2]

array([ 0, 33, 51], dtype=int32)

In [31]:
c[0:3,0:2,0:2]

array([[[ 7, 79],
        [56, 89]],

       [[58, 23],
        [20, 73]],

       [[72, 36],
        [54, 84]]], dtype=int32)

In [32]:
c[0:3,2,:]

array([[38, 76,  0],
       [96, 17, 33],
       [55, 64, 51]], dtype=int32)

In [33]:

c[:,2,:]


array([[38, 76,  0],
       [96, 17, 33],
       [55, 64, 51]], dtype=int32)

In [34]:
c[:,:,1]

array([[79, 89, 76],
       [23, 73, 17],
       [36, 84, 64]], dtype=int32)

In [35]:
dataset= np.random.randint(0,100,(16000,25))

In [36]:
dataset

array([[56,  4,  9, ..., 66, 53, 15],
       [ 9,  0, 41, ..., 16, 91, 26],
       [79,  0, 23, ..., 72, 40, 42],
       ...,
       [ 9, 10, 38, ..., 53, 83, 60],
       [97, 81, 92, ..., 50, 19, 69],
       [48, 33, 21, ...,  0, 15, 90]], shape=(16000, 25), dtype=int32)

In [37]:
dataset[:,0]

array([56,  9, 79, ...,  9, 97, 48], shape=(16000,), dtype=int32)

In [38]:
dataset[0,:] 

array([56,  4,  9, 16, 33, 84, 62, 75, 72, 58, 61, 86, 90, 41, 38, 54, 96,
       30, 12, 45, 10, 18, 66, 53, 15], dtype=int32)

In [39]:
dataset.shape

(16000, 25)

In [41]:
dataset[0,:] /100 # compress garera 0-1  ko bich ma liyera aayeko 

array([0.56, 0.04, 0.09, 0.16, 0.33, 0.84, 0.62, 0.75, 0.72, 0.58, 0.61,
       0.86, 0.9 , 0.41, 0.38, 0.54, 0.96, 0.3 , 0.12, 0.45, 0.1 , 0.18,
       0.66, 0.53, 0.15])

In [42]:
# usually sabbai row level mai access vairako xa 


### boolen haru use garera certain kura haru channu paro vane kasari garne ??? masking use garne 

In [45]:
d = np.random.randint(1,10,(5,5))

In [46]:
d

array([[6, 3, 9, 9, 5],
       [2, 9, 1, 8, 1],
       [9, 6, 9, 7, 6],
       [7, 5, 8, 1, 5],
       [1, 3, 5, 7, 8]], dtype=int32)

In [49]:
mask = d > 5 # conditional satisfaction 

In [50]:
mask

array([[ True, False,  True,  True, False],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True, False,  True, False, False],
       [False, False, False,  True,  True]])

In [51]:
d[mask] # so jun jun true xa teslai matra nikaera single row ma dine vayo 

array([6, 9, 9, 9, 8, 9, 6, 9, 7, 6, 7, 8, 7, 8], dtype=int32)

In [52]:
# customize mask 
maskk = [True,False,False,True,True]

In [53]:
d[maskk]

array([[6, 3, 9, 9, 5],
       [7, 5, 8, 1, 5],
       [1, 3, 5, 7, 8]], dtype=int32)

In [54]:
masskk=[[True,False],[False,True]]

In [55]:
d=[masskk]

In [56]:
d


[[[True, False], [False, True]]]

In [60]:
d = np.random.randint(1,10,(2,2))

In [61]:
d

array([[1, 6],
       [7, 4]], dtype=int32)

In [62]:
d[masskk]

array([1, 4], dtype=int32)

In [63]:
# if we want to mask we need to match the rows dimension

### build in methods for numpy

In [64]:
# Array Method

In [ ]:
#properties 

In [73]:
e = np.random.randint(10,50, size =(5,2,3) , dtype="int64")

In [74]:
e

array([[[48, 17, 32],
        [18, 21, 14]],

       [[45, 16, 15],
        [22, 29, 19]],

       [[17, 35, 21],
        [15, 30, 19]],

       [[48, 28, 21],
        [48, 26, 43]],

       [[28, 40, 23],
        [41, 20, 47]]])

In [76]:
(e.size * 64)

1920

In [77]:
#transpose garne 

In [78]:
e.T

array([[[48, 45, 17, 48, 28],
        [18, 22, 15, 48, 41]],

       [[17, 16, 35, 28, 40],
        [21, 29, 30, 26, 20]],

       [[32, 15, 21, 21, 23],
        [14, 19, 19, 43, 47]]])

In [80]:
e.reshape(2,3,5)

array([[[48, 17, 32, 18, 21],
        [14, 45, 16, 15, 22],
        [29, 19, 17, 35, 21]],

       [[15, 30, 19, 48, 28],
        [21, 48, 26, 43, 28],
        [40, 23, 41, 20, 47]]])

In [82]:
e.reshape(1,2,-1)


array([[[48, 17, 32, 18, 21, 14, 45, 16, 15, 22, 29, 19, 17, 35, 21],
        [15, 30, 19, 48, 28, 21, 48, 26, 43, 28, 40, 23, 41, 20, 47]]])

In [83]:
# array. ravel

In [86]:
e.ravel()

array([48, 17, 32, 18, 21, 14, 45, 16, 15, 22, 29, 19, 17, 35, 21, 15, 30,
       19, 48, 28, 21, 48, 26, 43, 28, 40, 23, 41, 20, 47])

In [87]:
e.flatten()

array([48, 17, 32, 18, 21, 14, 45, 16, 15, 22, 29, 19, 17, 35, 21, 15, 30,
       19, 48, 28, 21, 48, 26, 43, 28, 40, 23, 41, 20, 47])

In [88]:
e.reshape(2,3,5)

array([[[48, 17, 32, 18, 21],
        [14, 45, 16, 15, 22],
        [29, 19, 17, 35, 21]],

       [[15, 30, 19, 48, 28],
        [21, 48, 26, 43, 28],
        [40, 23, 41, 20, 47]]])

In [94]:
f = np.random.randint(1,10,(2,2,2))
f

array([[[3, 6],
        [3, 8]],

       [[3, 7],
        [3, 7]]], dtype=int32)

In [90]:
np.concatenate([e,f])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3 and the array at index 1 has size 2

In [95]:
g = np.random.randint(1,10,(2,2,2))
g

array([[[4, 4],
        [1, 6]],

       [[4, 9],
        [6, 6]]], dtype=int32)

In [96]:
np.concatenate([f,g])

array([[[3, 6],
        [3, 8]],

       [[3, 7],
        [3, 7]],

       [[4, 4],
        [1, 6]],

       [[4, 9],
        [6, 6]]], dtype=int32)

In [132]:
h = np.random.randint(1,10,(3,4))
h


array([[8, 3, 8, 5],
       [2, 3, 5, 9],
       [8, 8, 1, 3]], dtype=int32)

In [133]:
P = np.random.randint(1,10,(1,4))

In [134]:
P

array([[1, 7, 9, 6]], dtype=int32)

In [136]:
q = np.concatenate([h,P],axis=0)

In [137]:
q

array([[8, 3, 8, 5],
       [2, 3, 5, 9],
       [8, 8, 1, 3],
       [1, 7, 9, 6]], dtype=int32)

### axis 1 ma row milnu paro ani axis 0 ma column milnu paro 

In [142]:
np.split(q,2,axis=1) # colum ma split vayo 

[array([[8, 3],
        [2, 3],
        [8, 8],
        [1, 7]], dtype=int32),
 array([[8, 5],
        [5, 9],
        [1, 3],
        [9, 6]], dtype=int32)]

In [143]:
np.split(q,2,axis = 0)

[array([[8, 3, 8, 5],
        [2, 3, 5, 9]], dtype=int32),
 array([[8, 8, 1, 3],
        [1, 7, 9, 6]], dtype=int32)]

In [ ]:
 # spliting ma axis 1 rakhyo vane colum wise split hunxa 
# ani 0 rakhyo vane row 