In [1]:
import numpy as np

In [20]:
z = np.random.randint(1,50,(4,6))

In [22]:
z

array([[38, 43, 19, 16, 32, 23],
       [ 6,  6, 32, 46,  2, 22],
       [46, 10,  2, 29, 16, 26],
       [48, 37, 42, 41, 36, 45]], dtype=int32)

In [4]:
z.sum()

np.int64(144)

### Sum nikalna paro vane kam lagxa 

In [5]:
z.sum(axis=1)

array([43, 45, 29, 27])

In [6]:
z.sum(axis=0)

array([21, 20, 27, 24, 26, 26])

In [7]:
z.prod()

np.int64(192072198786048000)

In [8]:
z.prod(axis=1)

array([127008, 158760,   4200,   2268])

In [9]:
z.prod(axis=0)

array([ 630,  189, 1890,  441, 1440, 1344])

### Cummulative sum

In [10]:
z.cumsum()

array([  6,  13,  19,  26,  35,  43,  48,  57,  66,  73,  81,  88,  95,
        98, 103, 104, 109, 117, 120, 121, 128, 137, 141, 144])

In [11]:
z.cumsum(axis=0)

array([[ 6,  7,  6,  7,  9,  8],
       [11, 16, 15, 14, 17, 15],
       [18, 19, 20, 15, 22, 23],
       [21, 20, 27, 24, 26, 26]])

### max and min is to find maximum value from axis

In [12]:
z.max()

np.int32(9)

In [13]:
z.min()

np.int32(1)

In [14]:
z.max(axis=1)

array([9, 9, 8, 9], dtype=int32)

In [15]:
z.min(axis=1)

array([6, 5, 1, 1], dtype=int32)

In [16]:
z.max(axis=0)

array([7, 9, 9, 9, 9, 8], dtype=int32)

In [17]:
z.min(axis=0)

array([3, 1, 5, 1, 4, 3], dtype=int32)

In [21]:
z.argmax()

np.int64(18)

In [23]:
z.max()

np.int32(48)

In [24]:
z.argmax(axis=0)

array([3, 0, 3, 1, 3, 3])

In [25]:
z.argmax(axis=1)

array([1, 3, 0, 0])

In [31]:
z.clip(6,30) # clipping 

array([[30, 30, 19, 16, 30, 23],
       [ 6,  6, 30, 30,  6, 22],
       [30, 10,  6, 29, 16, 26],
       [30, 30, 30, 30, 30, 30]], dtype=int32)

### ELEMENT WISE OPERATION

In [45]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,5,8],[5,1,9]])

In [33]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[1, 5, 8],
        [5, 0, 9]]))

In [34]:
###Arthemetic Operation

In [35]:
a+b

array([[ 5, 10, 14],
       [10,  7, 18]])

In [36]:
np.add(a,b)

array([[ 5, 10, 14],
       [10,  7, 18]])

In [37]:
a-b

array([[ 3,  0, -2],
       [ 0,  7,  0]])

In [38]:
np.subtract(a,b)

array([[ 3,  0, -2],
       [ 0,  7,  0]])

In [39]:
a*b

array([[ 4, 25, 48],
       [25,  0, 81]])

In [40]:
np.multiply(a,b)

array([[ 4, 25, 48],
       [25,  0, 81]])

In [41]:
a**2

array([[16, 25, 36],
       [25, 49, 81]])

In [42]:
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]])

In [44]:
np.square(a)

array([[16, 25, 36],
       [25, 49, 81]])

In [46]:
a%b

array([[0, 0, 6],
       [0, 0, 0]])

In [49]:
np.divmod(a,b) # returns 2 array auta quotent ani arko vaneko reminder

(array([[4, 1, 0],
        [1, 7, 1]]),
 array([[0, 0, 6],
        [0, 0, 0]]))

In [50]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [51]:
np.sqrt(b)

array([[1.        , 2.23606798, 2.82842712],
       [2.23606798, 1.        , 3.        ]])

In [52]:
np.ceil(a)

array([[4, 5, 6],
       [5, 7, 9]])

In [53]:
np.floor(a)

array([[4, 5, 6],
       [5, 7, 9]])

In [55]:
np.ceil(ab)

array([[4., 1., 1.],
       [1., 7., 1.]])

In [56]:
new = 1/np.tan(b)

In [57]:
new

array([[ 0.64209262, -0.29581292, -0.14706506],
       [-0.29581292,  0.64209262, -2.21084541]])

In [58]:
np.round(new,decimals=2)

array([[ 0.64, -0.3 , -0.15],
       [-0.3 ,  0.64, -2.21]])

In [60]:
np.fix(new) ## towards 0 tira move vairaxa 

array([[ 0., -0., -0.],
       [-0.,  0., -2.]])

In [61]:
c=new

In [62]:
c

array([[ 0.64209262, -0.29581292, -0.14706506],
       [-0.29581292,  0.64209262, -2.21084541]])

In [66]:
np.int64(c)

array([[ 0,  0,  0],
       [ 0,  0, -2]])

In [67]:
np.floor(new)

array([[ 0., -1., -1.],
       [-1.,  0., -3.]])